apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app-dev

resources:
  - ../../../base/sample-app

images:
  - name: nginx
    newTag: "1.25.0"

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: sample-app
