apiVersion: v1
kind: ConfigMap
metadata:
  name: service-a-app-html
data:
  index.html.template: |
    <!DOCTYPE html>
    <html>
      <head><title>service-a</title></head>
      <body>
        <h1>service-a</h1>
        <p>Environment: ${ENVIRONMENT}</p>
        <p>Image tag: ${IMAGE_TAG}</p>
        <p>Served by nginx.</p>
      </body>
    </html>
