apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: sample-dev
          - env: stage
            namespace: sample-stage
  template:
    metadata:
      name: "sample-app-{{env}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/shirlenelss/argo-auto-promote.git
        targetRevision: main
        path: "repo/overlay/{{env}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
